#' Import R&A choice data from a CSV file generated by PsychTaskFramework
#'
#' @param filename A full file path to a .csv file created by PsychTaskFramework
#' @param save Should the function, as a side effect, save the processed file into a "clean/" directory?
#' @import readr
#' @import dplyr
#' @importFrom magrittr "%>%"
#' @return A clean R&A data frame
#' @export
importFromPTF <- function(filename, save = FALSE) {
  # TODO: Fix the 25/75% issue at this point or no?
  # x <- readr::read_csv(filename)
  x <- readr::read_csv(filename, na = c("", "NaN", "NA"))
  x <- x %>%
    dplyr::select(subjectId, choseLottery, probs, ambigs, stakes, colors,
                  starts_with('condition')) %>%
    dplyr::rename(ID = subjectId, choice = choseLottery, p = probs,
                  al = ambigs, val = stakes, redWins = colors)

  if (save) {
    # FIXME: This shouldn't be handled by the function
    write.csv(x, paste0('clean/', filename), row.names = FALSE)
  }

  return(x)
}
